### ISSUE TITLE
Suggestion: Turn this collection of tips into a github pages site.

### ISSUE THREAD

**Issue by staranbeer** [AllThingsSmitty/css-protips#153]
This is an awesome resource for whoever wants to learn more about CSS and its practical usage and i think a lot more people would benefit from it if the tips were in the form of documentation or bite sized blogs.

**Comment by AllThingsSmitty** [comment]
Thanks for the suggestion. It's an interesting idea and if I had the foresight when I started this repo years back I might have done it. Since then there have been several resources that have popped up as CSS resources like moderncss.dev, web.dev, and others. I don't think this would have the same impact or reach.
